# Generated by Django 5.2.5 on 2025-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                ("platform", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("rating", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
