# Generated by Django 5.2.5 on 2025-09-06 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-release_date"]},
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="game",
            name="platform",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
